# Generated by Django 5.2.8 on 2026-01-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_make_customer_required_and_cleanup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductEntry',
        ),
    ]
